### PR TITLE
Implement placeholder text for FakeCurrencyInput

### PR DESCRIPTION
**Pull request by ajp8164**
Allow placeholder and placeholderTextColor to be used with FakeCurrencyInput. Also update position to move cursor slightly left to provide improved appearance.

Update - exposes caretStyle as well to refine desired caret presentation. Implementation is backward compatible with caretColor and caretHidden.

### CODE REVIEW

**Review by CaioQuirinoMedeiros — CHANGES_REQUESTED** [review]
A View component inside a Text component causes a crash. I'd recommend to just undo this part

**Comment by ajp8164** [comment]
Can this be approved and merged? Happy to work in any required changes.

**Comment by renattomartins** [comment]
Hi! What is needed to approve this pr? :)

**Comment by jtdaugh** [comment]
This PR looks great can we get it merged?

**Review by CaioQuirinoMedeiros — APPROVED** [review]

**Comment by CaioQuirinoMedeiros** [comment]
Sorry, i messed up the merge because of formatting conflicts, but it's on 1.1.1

**Comment by renattomartins** [comment]
Thanks!

**Pull request closed without merging**
